#!/bin/sh

set -u

POS=$(dirname $(realpath $0))

direnv_conf=${HOME}/.config/direnv/
tmux_conf=${POS}/../dotfile/.tmux.conf
emacs_conf=${POS}/../dotfile/.emacs
emacs_rime_datadir=${HOME}/.emacs.d/rime
bash_profile=${POS}/../dotfile/.bash_profile
bashrc=${POS}/../dotfile/.bashrc.container
git_conf=${POS}/../dotfile/.gitconfig

export GUIX_ENVIRONMENT_CONTAINER="dev"
export EDITOR='emacsclient -nw'
guix environment --container \
     --no-cwd \
     --network \
     -E^GUIX_ENVIRONMENT_CONTAINER$ \
     --expose=${bash_profile}=${HOME}/.bash_profile \
     --expose=${bashrc}=${HOME}/.bashrc \
     --share=${direnv_conf}=/${HOME}/.config/direnv \
     --ad-hoc direnv bash \
     --ad-hoc glibc-utf8-locales ncurses \
     --preserve=^TERM$ \
     --preserve=^LANG$ \
     --preserve=^GUIX_LOCPATH$ \
     --ad-hoc tmux \
     --expose=${tmux_conf}=${HOME}/.tmux.conf \
     --ad-hoc nss-certs curl \
     --expose=/etc/ssl \
     --ad-hoc git \
     --expose=${git_conf}=${HOME}/.gitconfig \
     --ad-hoc emacs-next \
     --expose=${emacs_conf}=${HOME}/.emacs \
     --preserve=^EDITOR$ \
     --ad-hoc emacs-rime \
     --share=${emacs_rime_datadir}=${HOME}/.emacs.d/rime \
     --ad-hoc emacs-ggtags global gcc-toolchain gdb\
     --ad-hoc guile guix emacs-paredit emacs-magit emacs-geiser \
     --ad-hoc emacs-which-key \
     --ad-hoc emacs-sdcv sdcv stardict-ecdict \
     --ad-hoc emacs-debbugs \
     --ad-hoc make cmake\
     --ad-hoc bash coreutils findutils diffutils patch gawk sed grep inetutils texinfo man-db gzip bzip2 xz zstd less psmisc procps htop\
     --ad-hoc sicp man-pages \
     "$@"
